---
title: "Deliverable 2: Bivariate Plot"
output: html_notebook


```{r}
#install.packages("tidyverse")
library(ggplot2)
library(lubridate)
```

```{r collect, eval=TRUE}
# clear memory
rm(list = ls())
# collecting the data
link='https://github.com/Data-Visual-Masters/Deliverable2/raw/main/Fremont_Bridge_Bicycle_Counter.csv'
fremont=read.csv(link)
```


Let's see what kind of data we have in our data table:

```{r str, eval=TRUE}
# categorical? numerical?
str(fremont,width = 50,strict.width='cut')
```
```{r}
#sets our date variable format as m/d/y
fremont$Date=as.Date(fremont$Date,format = "%m/%d/%Y")
```

```{r}
#sets our bridge count variable to numeric
fremont$Fremont.Bridge.Total=as.numeric(fremont$Fremont.Bridge.Total)
```


```{r}
aggregate(data=fremont,Fremont.Bridge.Total~Date,FUN =sum )
```

```{r}
#produces base line graph with transparency
base=ggplot(fremont,
            aes(x=Date,y=Fremont.Bridge.Total))
base  + geom_line(alpha=0.3) 
```

```{r, eval=TRUE}
#limits x axis to 2020 and beyond
start <- as.Date("2020-1-1")
end <- NA
base=ggplot(fremont,
            aes(x=Date,y=Fremont.Bridge.Total))
base  + geom_line(alpha=0.3) + scale_x_date(limits = c(start, end)) 
```


```{r, eval=TRUE}
base=ggplot(fremont,
            aes(x=floor_date(Date, "month"),
                y=Fremont.Bridge.Total))
monthly= base  + geom_line(alpha=0.3) 
monthly= monthly + scale_x_date(limits = c(start, end))
monthly
```


```{r, eval=TRUE}
#attempt at analyzing monthly data
base=ggplot(fremont,
            aes(x=Date,
                y=Fremont.Bridge.Total))
monthly= base  + geom_line(alpha=0.3) 
monthly= monthly + scale_x_date(limits = c(start, end))
# adding a trend:
monthly = monthly + stat_smooth(color = "red",
                      method = "loess")
#monthly + facet_wrap(~crime)
monthly
```

```{r ggscatter, eval=TRUE}
library(ggrepel)
monthly + geom_text_repel(aes(label=Fremont.Bridge.Total))
```

```{r}
monthly + geom_text_repel(aes(label=Fremont.Bridge.Total),size=2,
                        min.segment.length = 0,
                        max.overlaps = 100)
```


Now we can limit the labels

```{r, eval=TRUE}
monthly + geom_text_repel(aes(label=ifelse(Fremont.Bridge.Total>=700,Fremont.Bridge.Total, "")),size=2,
                        min.segment.length = 0,
                        max.overlaps = 100)
```

```{r}
#Referenced monthly as base plot, but lost annotations here from last line of code
monthly
```

```{r}
# Defining the title
the_Title="Frequency of Bike Use on Fremont Bridge"
the_Subtitle="Jan 2020 - Dec 2022"
# Adding the titles
monthly2= monthly + ggtitle (label = the_Title,
                             subtitle = the_Subtitle)
# Run plot again
monthly2
```

```{r}
# Axes titles to be used
horizontalTitle = "Date"
verticalTitle = "Number of Bike Trips"
# Adding the titles to the axes
monthly3 = monthly2 +xlab(horizontalTitle) + ylab (verticalTitle)
# Run plot again
monthly3

```

```{r}
# Adding the data source
theSource = "Source: Seattle Open Data Portal (City of Seattle, 2022)"
# Adding the source
monthly4 = monthly3 + labs(caption = theSource)
# Run the plot
monthly4
```

```{r}
# Getting rid of background
monthly5 = monthly4 + theme_classic()
# Run plot
monthly5
```

